services:
  app:
    image: ir0h/resos_menu
    ports:
      - ${APP_PORT}:80
    environment:
      DATABASE_URL: postgresql://postgres:20453843@resos_menu_postgres:${DB_PORT}/resos_menu_db
    restart: always
    depends_on:
      - resos_menu_postgres
    networks:
      - menu_net
    volumes:
      - type: volume
        source: static_data
        target: /app/app/static

  resos_menu_postgres:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 20453843
      POSTGRES_DB: resos_menu_db
    networks:
      - menu_net

volumes:
  static_data:
  postgres-data:

networks:
  menu_net:
    external: true