services:
  app:
    image: ir0h/resos_menu
    ports:
      - 127.0.0.1:8010:80
    environment:
      DATABASE_URL: postgresql://postgres:20453843@resos_menu_postgres:5432/resos_menu_db
    depends_on:
      - resos_menu_postgres
    networks:
      - frontnet

  resos_menu_postgres:
    image: postgres
    volumes:
      - resos-menu-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 20453843
      POSTGRES_DB: resos_menu_db
    networks:
      - frontnet

volumes:
  resos-menu-postgres-data:

networks:
  frontnet:
    external: true